name: pdfium
description: dart:ffi wrapper for Google's Pdfium library
version: 0.0.1
homepage: https://github.com/scientifichackers/flutter-pdfium
author: Dev Aggarwal <devxpy@gmail.com>

environment:
  sdk: ">=2.6.0-dev.8.2 <3.0.0"

dependencies:
  ffi: 0.1.3-dev.3
  image: ^2.1.0
